Repository thoughtbot/shoulda-matchers, pull requests merged in 2020-07, with the labels that each got.

#992 pass correct object type to association reflection
  lib/shoulda/matchers/active_record/association_matchers/model_reflection.rb
  lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb
  spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb
  spec/unit/shoulda/matchers/active_record/association_matchers/model_reflection_spec.rb
Labels: ⏱ PR: In Queue for Review

#995 uniqueness: don't use a private Rails API
  lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
Labels: ⏱ PR: In Queue for Review

#1190 Bug fix: uniqueness validation fails with scoped attributes of data type time
  lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
  lib/shoulda/matchers/util.rb
  spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb
Labels: ⏱ PR: In Queue for Review

#1243 Add have_implicit_order_column matcher
  lib/shoulda/matchers/active_record.rb
  lib/shoulda/matchers/active_record/have_implicit_order_column.rb
  lib/shoulda/matchers/rails_shim.rb
  spec/support/unit/active_record/create_table.rb
  spec/support/unit/helpers/active_record_versions.rb
  spec/support/unit/helpers/model_builder.rb
  spec/support/unit/rails_application.rb
  spec/unit/shoulda/matchers/active_record/have_implicit_order_column_spec.rb
Labels: 🏃‍♀️PR: In Progress

#1194 Started on ActiveStorage matchers
  lib/shoulda/matchers/active_record.rb
  lib/shoulda/matchers/active_record/have_attached_matcher.rb
  spec/support/unit/helpers/active_record_versions.rb
  spec/support/unit/helpers/rails_versions.rb
  spec/unit/shoulda/matchers/active_record/have_attached_matcher_spec.rb
Labels: PR: Feature, 🏃‍♀️PR: In Progress
